### ISSUE TITLE
Example doesn't compile: platform undefined

### ISSUE THREAD

**Issue by remoteportal** [PlugFox/platform_info#11]
Trying to figure out how to determine if debug/build release but the example doesn't compile because platform variable isn't declared on this line:

`final string = platform.when(`

**Comment by PlugFox** [comment]
@remoteportal 
`platform` is global getter
https://github.com/PlugFox/platform_info/blob/master/lib/platform_info.dart#L46

Are u import `import 'package:platform_info/platform_info.dart';` in file?
And use version: `platform_info: ^3.0.0` in pubspec.yaml?

**Comment by PlugFox** [comment]
@remoteportal what version of `platform_info` you use?

**Comment by remoteportal** [comment]
I must have been in some type of confusion yesterday because now it is working.  Please disregard.  Sorry.
