### ISSUE TITLE
Windows 11 is not detected

### ISSUE THREAD

**Issue by JCKodel** [PlugFox/platform_info#18]
![image](https://github.com/PlugFox/platform_info/assets/379339/7ef99bb0-04f1-4bdc-b9f8-002326d4c3f1)

`platform.version` = `"Windows 10 Pro" 10.0 (Build 22621)`

**Comment by PlugFox** [comment]
@JCKodel thats came from [dart:io Platform.operatingSystemVersion](https://api.flutter.dev/flutter/dart-io/Platform/operatingSystemVersion.html)

And linked issues: 
https://github.com/dart-lang/sdk/issues/47334
https://learn.microsoft.com/en-us/answers/questions/586619/windows-11-build-ver-is-still-10-0-22000-194

You can parse it by yourself and, based on `build version` precisely detect the operating system version.

> build number >= 22000 = Windows 11

This package only provides a universal handy API between VM and JS environments without additional logic.
