### ISSUE TITLE
IP address and hostname

### ISSUE THREAD

**Issue by pulstar** [PlugFox/platform_info#2]
I would like to get the browser name, version, user agent, etc. Is it possible to do this with platform_info?
I did try to install the package platform_detect, but it doesn't work and platform_info is far better.  
Look at this example: https://github.com/Workiva/platform_detect/blob/master/example/main.dart

Also, I want to get the user IP address and hostname. 
I can do that with the get_ip package, but it only works for Android and iOS. 
Is it possible to get such information with platform_info?

By the way, thank you for your great package! It save my day!

**Comment by PlugFox** [comment]
@pulstar 

> I would like to get the browser name, version, user agent, etc. Is it possible to do this with platform_info?

Yes, use `platform.version` and parse this string like this: `final isChrome = platform.version.toLowerCase().contains('chrome');`
But be careful, browsers do not guarantee the format of this line.

> Also, I want to get the user IP address and hostname.

You cannot get ip and hostname without making an http request.
The browser does not have API for this things.

The main concept of the package is full cross-platform functionality.
Everything that is available in the browser should work in the console and on the desktop and on the mobile device in the same way.

If you have any questions, I will reopen this issue.

**Comment by pulstar** [comment]
Hi there! Thank you for your promptly answers.

About getting the IP address, I implemented a solution, so don't bother about it. By the way, I am getting some errors in the browser console. Could you take a look to see if this have anything to do with your package? Thank you!

```
Overflow on channel: flutter/platform.  Messages on this channel are being discarded in FIFO fashion.  
The engine may not be running or you need to adjust the buffer size if of the channel.
_debugPrintWarning @ main.dart.js:14807
2main.dart.js:83242 Uncaught PlatformException(error, Unsupported operation: Unrecognized JSON message, null, null)
    at Object.wrapException (https://domain.com/main.dart.js:5717:17)
    at StandardMethodCodec.decodeEnvelope$1 (https://domain.com/main.dart.js:150799:17)
    at https://domain.com/main.dart.js:150916:46
    at _wrapJsFunctionForAsync_closure.$protected (https://domain.com/main.dart.js:9331:15)
    at _wrapJsFunctionForAsync_closure.call$2 (https://domain.com/main.dart.js:80220:12)
    at _awaitOnObject_closure.call$1 (https://domain.com/main.dart.js:80206:32)
    at _RootZone.runUnary$2$2 (https://domain.com/main.dart.js:83369:18)
    at _Future__propagateToListeners_handleValueCallback.call$0 (https://domain.com/main.dart.js:81173:51)
    at Object._Future__propagateToListeners (https://domain.com/main.dart.js:9582:93)
    at _Future._completeWithValue$1 (https://domain.com/main.dart.js:80995:9)
```

**Comment by pulstar** [comment]
Thank you for the answers. Following your tips, I managed to create a cloud function to get the user's IP address. It worked fine.
